INSERT INTO ingredients(name) VALUES ('eggs');
INSERT INTO ingredients(name) VALUES ('milk');
INSERT INTO ingredients(name) VALUES ('garlic');
INSERT INTO ingredients(name) VALUES ('salt');
INSERT INTO ingredients(name) VALUES ('pepper');
INSERT INTO ingredients(name) VALUES ('cheddar cheese');
INSERT INTO ingredients(name) VALUES ('olive oil');
INSERT INTO ingredients(name) VALUES ('yellow onion');
INSERT INTO ingredients(name) VALUES ('water');
INSERT INTO ingredients(name) VALUES ('broccoli');
INSERT INTO ingredients(name) VALUES ('spinach');
INSERT INTO ingredients(name) VALUES ('green onion');
INSERT INTO ingredients(name) VALUES ('grape tomatoes');
INSERT INTO ingredients(name) VALUES ('cilantro');
INSERT INTO ingredients(name) VALUES ('lime juice');
INSERT INTO ingredients(name) VALUES ('red pepper flakes');
INSERT INTO ingredients(name) VALUES ('monterey jack cheese');
INSERT INTO ingredients(name) VALUES ('avacado');
INSERT INTO ingredients(name) VALUES ('black beans');
INSERT INTO ingredients(name) VALUES ('rolled oats');
INSERT INTO ingredients(name) VALUES ('ground cinnamon');
INSERT INTO ingredients(name) VALUES ('ground ginger');
INSERT INTO ingredients(name) VALUES ('coconut oil');
INSERT INTO ingredients(name) VALUES ('maple syrup');
INSERT INTO ingredients(name) VALUES ('vanilla extract');
INSERT INTO ingredients(name) VALUES ('coconut flakes');
INSERT INTO ingredients(name) VALUES ('dried fruits');
INSERT INTO ingredients(name) VALUES ('sweet potato');
INSERT INTO ingredients(name) VALUES ('cayenne pepper');
INSERT INTO ingredients(name) VALUES ('chili pepper');
INSERT INTO ingredients(name) VALUES ('cumin');
INSERT INTO ingredients(name) VALUES ('corn tortilla');
INSERT INTO ingredients(name) VALUES ('crumbled feta cheese');
INSERT INTO ingredients(name) VALUES ('basil');
INSERT INTO ingredients(name) VALUES ('green pumpkin seeds');
INSERT INTO ingredients(name) VALUES ('lemon juice');
INSERT INTO ingredients(name) VALUES ('zucchini');
INSERT INTO ingredients(name) VALUES ('kale');
INSERT INTO ingredients(name) VALUES ('carrots');
INSERT INTO ingredients(name) VALUES ('jalapenos');
INSERT INTO ingredients(name) VALUES ('radish');
INSERT INTO ingredients(name) VALUES ('tahini');
INSERT INTO ingredients(name) VALUES ('quinoa');
INSERT INTO ingredients(name) VALUES ('unsalted butter');
INSERT INTO ingredients(name) VALUES ('honey');
INSERT INTO ingredients(name) VALUES ('fusilli pasta');
INSERT INTO ingredients(name) VALUES ('olives');
INSERT INTO ingredients(name) VALUES ('chickpeas');
INSERT INTO ingredients(name) VALUES ('parsley leaves');
INSERT INTO ingredients(name) VALUES ('cauilflower');
INSERT INTO ingredients(name) VALUES ('peaches');
INSERT INTO ingredients(name) VALUES ('greek yogurt');
INSERT INTO ingredients(name) VALUES ('almond butter');
INSERT INTO ingredients(name) VALUES ('semi sweet chocolate');
INSERT INTO ingredients(name) VALUES ('cinnamon');
INSERT INTO ingredients(name) VALUES ('all purpose flour');
INSERT INTO ingredients(name) VALUES ('whole pecans');
INSERT INTO ingredients(name) VALUES ('peppermint extract');
INSERT INTO ingredients(name) VALUES ('dark chocolate');