-- psql -a -f seedRecipes.sql
\c vegetarian_meals;

INSERT INTO recipes (meal, name, image_url, description, instructions) VALUES ('Breakfast','Broccoli Cheddar and Spinach Frittata', 'http://cookieandkate.com/images/2017/02/broccoli-cheddar-frittata.jpg','This spinach, broccoli and cheddar frittata recipe is a simple breakfast, brunch or dinner!', 'Preheat the oven to 425 degrees. In a large bowl, add eggs, 
	milk, garlic 1/4 teaspoon of the salt and pepper until blended. Then whisk in about half of the cheese, save other half for later. In skillet warm up olive oil over medium heat. Add onions and salt for 3 minutes. Add broccoli and water to pan, cover with lid and steam the mixture about 3 minutes. Uncover add the spinach and onions, stir constantly. Arrange the mixture in a even layer across the skillet. Whisk egg mixture one last time and pour into pan. 
	Add the remaining cheese, put in oven for 12 minutes.');

INSERT INTO recipes (meal, name, image_url, description, instructions) VALUES ('Breakfast','Tex-Mex Breakfast Bowl', 'http://cookieandkate.com/images/2016/06/breakfast-bowl-with-eggs-black-beans-pico.jpg','Hearty breakfast bowls featuring your favorite Tex-Mex flavors, including fresh pico de gallo, black beans and avocado.', 'In a medium saucepan over medium heat, warm the olive oil until shimmering. Add the chopped onion and a sprinkle of salt. Cook, stirring occassionally, until onions has soften about 5-8 minutes. Add cumin and garlic. Pour in the black beans and water, stir, cook for 5 minutes. Reduce heat use a fork to mash up half of the beans. Continue to cook the beans, uncovered, about 3 minutes. Remove from heat, add lime juice, salt and pepper. Scamble eggs with the milk and add some pepper and red pepper flakes. Warm up pan with olive oil over medium heat,pour in eggs. 
	Place in bowl when finished with slices of avacado.');

INSERT INTO recipes (meal, name, image_url, description, instructions) VALUES ('Breakfast','Triple Coconut Granola', 'http://laurencariscooks.com/1_lcc/wp-content/uploads/2017/02/Cacao-Crunch-Granola-1-2-600x600.jpg','This easy homemade coconut granola recipe features coconut flakes, shredded coconut and coconut oil!', ' Preheat oven to 350 degrees and line a large rimmed baking sheet with parchment paper. 
	In a large mixing bowl, combine the oats, almonds, cinnamon, salt and ground ginger. Add the coconut oil, maple syrup and vanilla. Stir until every oat is lightly and evenly coated. Spread the oats onto the baking sheet evenly. 
	Bake for 15 minutes, once done baking remove from oven and add both the coconut flakes.');

INSERT INTO recipes (meal, name, image_url, description, instructions) VALUES ('Dinner','Sweet Potato and Black Bean Tacos', 'http://cookieandkate.com/images/2017/02/sweet-potato-black-bean-tostadas-recipe.jpg','This vegetarian tostadas recipe features roasted sweet potatoes and healthy "refried" black beans, served on a bed of crisp salad.', 'Roast sweet potatoes, preheat oven to 425 degrees, add olive oil, cayenne pepper and salt to the potatoes. Bake for 40 minutes. To prepare the black beans, warm olive oil in a pan over medium heat. Add the onions and salt, cook for about 5-8 minutes. Add the cummin and chili powder. Pour in the beans with water, reduce the heat to a gentle simmer. Cook for 5 minutes.  When done, mash beans, season with salt and pepper. Once the sweet potatoes are done assemble taco and add feta crumbles and cilantro for garnish!');

INSERT INTO recipes (meal, name, image_url, description,instructions) VALUES ('Dinner','Zucchini Noodles with Basil Pumpkin Seed Pesto','http://cookieandkate.com/images/2016/06/zoodles-with-pesto-and-tomatoes.jpg', 'Fresh, raw zucchini noodles tossed with basil pesto and cherry tomatoes make a light, healthy meal.', 'Prepare the pesto: in a food processor, combine the onion, garlic, basil, olive oil and red pepper flakes. Blend until smooth then season with salt. To prepare the noodles: Sprialize the zucchini, toss the zucchini with the pesto until its coated completely and season again with salt. Transfer the fresh basil into the corners to garnish.');

INSERT INTO recipes (meal, name, image_url, description, instructions) VALUES ('Dinner','Simple Kale Salad','http://cookieandkate.com/images/2016/05/anything-goes-kale-salad-recipe-2.jpg','This super versatile kale salad features an amazing tahini dressing.', 'To prepare the kale: remove the center ribs from the kale and chop into small pieces. Season with salt and massage the kale until the kale turns a darker green. Combine the kale with any veggies perferred, add green pumpkin seeds. Drizzle the green tahini dressing.Enjoy!');

INSERT INTO recipes (meal, name, image_url, description, instructions) VALUES ('Side','Roasted Carrots with Honey','http://cookieandkate.com/images/2016/03/roasted-carrots-with-honey-butter-recipe.jpg','Simple roasted carrots tossed in a light honey butter sauce makes an incredible side dish!', 'Preheat oven to 425 degrees. Cut carrots in half width. Toss the carrots with the olive oil and salt. Spread them out on a pan, bake for 40 minutes. At 35 minutes make the honey butter, melt butter in medium saucepan about 2 minutes and then stir in honey once removed from the heat. When carrots are done remove from oven place in a bowl and drizzle over the honey butter and season with pepper.');

INSERT INTO recipes (meal, name, image_url, description,instructions) VALUES ('Side', 'Pesto Pasta Salad','http://cookieandkate.com/images/2016/10/pesto-pasta-salad.jpg', 'This pesto pasta salad recipe is bursting with fresh flavor.', 'Preheat oven to 425 degrees, line baking sheet with parchment paper. Cut off the nubby base of the cauilflower, then cut into four quarters. Add olive oil, salt and pepper. Bake for 40 minutes or until tops get golden.');

INSERT INTO recipes (meal, name, image_url, description,instructions) VALUES ('Side','Roasted Cauliflower', 'http://cookieandkate.com/images/2016/10/roasted-cauliflower-with-parmesan-parsley.jpg', 'So easy to make and oh so yummy!', 'Bring a large pot of salted water to a boil. Add pasta until al dente, before draining, reserve 1/2 cup pasta cooking water and then drain the rest and immediately rinse with cool water.  While pasta is cooking, prepare the pesto: in a small skillet add the green pumpkin seeds for 5 minutes, then add into food processor adding olive oil. Pour pesto over the pasta with the left over water.  Add tomatoes, spinach, chickpeas and olives. Add some lemon juice and salt on top.');

INSERT INTO recipes (meal, name, image_url, description,instructions) VALUES ('Dessert','Creamy Peach and Honey Popsicles', 'http://cookieandkate.com/images/2015/08/peach-popsicles-5.jpg', 'These cold, creamy treats are perfect for summertime.', 'Preheat oven at 350 degrees. Add sliced peaches to the baking sheet and toss honey and a dash of salt. Roast peaches for 30-40 minutes, check half way. Blend together yogurt,honey, lemon juice and vanilla extract in a medium bowl. Place mixture in refrigerator. Once peaches are done in the oven, let cool and then scrape the them into the bowl of yogurt. Scoop yogurt mixture into the popsicle molds, insert popsicle sticks and freeze for at least 4 hours.');

INSERT INTO recipes (meal, name, image_url, description,instructions) VALUES ('Dessert','Salted Oat Fudge', 'http://cookieandkate.com/images/2014/12/healthy-fudge-recipe.jpg', 'It tastes like a cross between fudge and no-bake cookies.', 'Preheat oven to 325 degrees. Toast the nuts: arrange the nuts in a single layer and make for 7 minutes. Chop into tiny pieces. Making the fudge: in a medium size pot combine butter, chocolate chips, salt and cinnamon. Warm the pot over medium heat and stir often. Stir in vanilla extract followed by the rolled oats and pecans. Carefully dump the fudge onto a baking sheet, distribute evenly. Cover and freeze for 30-45 minutes. If not in a hurry leave for at least an hour. Once firm, cut into squares.');

INSERT INTO recipes (meal, name, image_url, description,instructions) VALUES ('Dessert','Chocolate Peppermint Cups', 'http://cookieandkate.com/images/2017/02/honey-sweetened-chocolate-peppermint-cups-3.jpg', 'These dark chocolate treats are fun and easy to make!', 'In a small bowl, stir honey and peppermint extract together. Arrange mini cupcake liners on a large plate. Melt chocolate,fill the bottoms of each p with melted chocolate. Add a small dollop of the honey mixture in the center and then add more melted chocolate. Sprinkle salt over the cups. Freeze until firm, about 30 minutes.');
